---用户信息表-
CREATE TABLE TB_FLOWER_USER(
   USER_ID INTEGER PRIMARY KEY,
   USER_NAME VARCHAR2(64),
   TRUE_NAME VARCHAR2(64),
   PASSWORD VARCHAR2(64),
   USER_SEX INTEGER,
   ADDRESS VARCHAR2(256),
   TELEPHONE VARCHAR2(32),
   POSTALCODE INTEGER,
   USER_ROLE INTEGER,
   USER_STATUS INTEGER,
   REGISTER_TIME DATE,
   UPDATE_TIME DATE,
   ADVANCE_PAYMENT NUMBER(8,2)
 )
CREATE SEQUENCE GEN_FLOWER_USER INCREMENT BY 1 START WITH 10000
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_FLOWER_USER
    BEFORE INSERT ON TB_FLOWER_USER FOR EACH ROW
BEGIN
    SELECT GEN_FLOWER_USER.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
 
 ---鲜花信息表--
 CREATE TABLE TB_FLOWER_FLOWER(
   ID INTEGER PRIMARY KEY,
   FLOWER_NAME VARCHAR2(64),
   MATERIAL VARCHAR2(64),
   PURPOSE VARCHAR2(64),
   FOR_DATE VARCHAR2(256),
   FOR_PEOPLE VARCHAR2(32),
   BRIEFINFO INTEGER,
   ISPREFERENCE INTEGER,
   PRICE NUMBER(5,2),
   PREFERENCEPRICE NUMBER(5,2),
   PICTUREPATH VARCHAR2(256),
   STORECOUNT INTEGER,
   CREATEDATE DATE
)
CREATE SEQUENCE GEN_FLOWER_FLOWER INCREMENT BY 1 START WITH 10000
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_FLOWER_FLOWER
    BEFORE INSERT ON TB_FLOWER_FLOWER FOR EACH ROW
BEGIN
    SELECT GEN_FLOWER_FLOWER.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


--订单信息表--

CREATE TABLE TB_FLOWER_ORDER(
	ID INTEGER PRIMARY KEY,
	ORDER_NUMBER VARCHAR2(64),
	USER_NAME  VARCHAR2(64),
	CREATE_DATE DATE,
	RECEIVEPERSON_NAME VARCHAR2(64),
	RECEIVE_ADDRESS VARCHAR2(256),
	RECEIVE_POSTALCODE INTEGER,
	RECEIVE_TEL  VARCHAR2(32),
	REMARK  VARCHAR2(256)
)
CREATE SEQUENCE GEN_FLOWER_ORDER INCREMENT BY 1 START WITH 10000
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_FLOWER_ORDER
    BEFORE INSERT ON TB_FLOWER_ORDER FOR EACH ROW
BEGIN
    SELECT GEN_FLOWER_ORDER.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--订单详细内容表--
CREATE TABLE TB_FLOWER_DETAIL_INFO(
	ID INTEGER PRIMARY KEY,
	ORDER_NUMBER VARCHAR2(64),
	FLOWER_ID INTEGER,
	DISCOUNT INTEGER,
	SINGLE_PRICE NUMBER(8,2)
)
CREATE SEQUENCE GEN_FLOWER_DETAIL_INFO INCREMENT BY 1 START WITH 10000
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_FLOWER_DETAIL_INFO
    BEFORE INSERT ON TB_FLOWER_DETAIL_INFO FOR EACH ROW
BEGIN
    SELECT GEN_FLOWER_DETAIL_INFO.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--评论信息表---
CREATE TABLE TB_FLOWER_COMMENT(
	ID INTEGER PRIMARY KEY,
	USER_NAME VARCHAR2(64),
	COMMENT_TIME DATE,
	CONTENT VARCHAR2(256)
)
CREATE SEQUENCE GEN_FLOWER_COMMENT INCREMENT BY 1 START WITH 10000
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_FLOWER_COMMENT
    BEFORE INSERT ON TB_FLOWER_COMMENT FOR EACH ROW
BEGIN
    SELECT GEN_FLOWER_COMMENT.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
































